Nama:

Rahman Aziz Firmansyah

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder, StandardScaler, MinMaxScaler, RobustScaler, MaxAbsScaler, OneHotEncoder
from sklearn.feature_selection import mutual_info_classif
import scipy.stats as st

(1) Import 'employee.csv' menjadi DataFrame. Drop kolom yang dianggap tidak diperlukan dalam pembuatan model klasifikasi. Subset kolom 'Attrition' dalam variabel y dan Subset kolom lainnya dalam variabel X.

In [2]:
employee = pd.read_csv('employee.csv')
employee

,EmployeeNumber,Attrition,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1,Yes,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,...,1,80,0,8,0,1,6,4,0,5
1,2,No,49,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,...,4,80,1,10,3,3,10,7,1,7
2,3,Yes,37,Travel_Rarely,1373,Research & Development,2,2,Other,4,...,2,80,0,7,3,3,0,0,0,0
3,4,No,33,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,...,3,80,0,8,3,3,8,7,3,0
4,5,No,27,Travel_Rarely,591,Research & Development,2,1,Medical,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2935,2936,No,36,Travel_Frequently,884,Research & Development,23,2,Medical,3,...,3,80,1,17,3,3,5,2,0,3
2936,2937,No,39,Travel_Rarely,613,Research & Development,6,1,Medical,4,...,1,80,1,9,5,3,7,7,1,7
2937,2938,No,27,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2,...,2,80,1,6,0,3,6,2,0,3
2938,2939,No,49,Travel_Frequently,1023,Sales,2,3,Medical,4,...,4,80,0,17,3,2,9,6,0,8
2939,2940,No,34,Travel_Rarely,628,Research & Development,8,3,Medical,2,...,1,80,0,6,3,4,4,3,1,2

In [3]:
#mendrop kolom EmployeeNumber karena kolom tersebut tidak bermakna
employee = employee.drop('EmployeeNumber', axis=1)
#mendrop kolom dengan value yang seragam
for col in employee.columns:
    if len(employee[col].unique()) == 1:
        employee.drop(col, axis=1, inplace=True)
        print(f"{col} has been dropped")
employee

Over18 has been dropped
StandardHours has been dropped

,Attrition,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,Yes,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,No,49,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,Yes,37,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,No,33,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,No,27,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2935,No,36,Travel_Frequently,884,Research & Development,23,2,Medical,3,Male,...,3,3,1,17,3,3,5,2,0,3
2936,No,39,Travel_Rarely,613,Research & Development,6,1,Medical,4,Male,...,3,1,1,9,5,3,7,7,1,7
2937,No,27,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2,Male,...,4,2,1,6,0,3,6,2,0,3
2938,No,49,Travel_Frequently,1023,Sales,2,3,Medical,4,Male,...,3,4,0,17,3,2,9,6,0,8
2939,No,34,Travel_Rarely,628,Research & Development,8,3,Medical,2,Male,...,3,1,0,6,3,4,4,3,1,2

In [4]:
X = employee[employee.columns[employee.columns != 'Attrition']]
y = employee['Attrition']

In [5]:
X

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,HourlyRate,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,94,...,3,1,0,8,0,1,6,4,0,5
1,49,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,61,...,4,4,1,10,3,3,10,7,1,7
2,37,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,92,...,3,2,0,7,3,3,0,0,0,0
3,33,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,56,...,3,3,0,8,3,3,8,7,3,0
4,27,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,40,...,3,4,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2935,36,Travel_Frequently,884,Research & Development,23,2,Medical,3,Male,41,...,3,3,1,17,3,3,5,2,0,3
2936,39,Travel_Rarely,613,Research & Development,6,1,Medical,4,Male,42,...,3,1,1,9,5,3,7,7,1,7
2937,27,Travel_Rarely,155,Research & Development,4,3,Life Sciences,2,Male,87,...,4,2,1,6,0,3,6,2,0,3
2938,49,Travel_Frequently,1023,Sales,2,3,Medical,4,Male,63,...,3,4,0,17,3,2,9,6,0,8
2939,34,Travel_Rarely,628,Research & Development,8,3,Medical,2,Male,82,...,3,1,0,6,3,4,4,3,1,2

In [6]:
y

0       Yes
1        No
2       Yes
3        No
4        No
       ...
2935     No
2936     No
2937     No
2938     No
2939     No
Name: Attrition, Length: 2940, dtype: object

(2) Split X dan y menjadi X_train, X_test, y_train, y_test dengan test size 0.2 dan pastikan rasio label pada y_train dan y_test seimbang.

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [8]:
#memastikan rasio label pada y_train dan y_test seimbang
#rasio yes dan no pada y_train
y_train.value_counts()/len(y_train)

No     0.838861
Yes    0.161139
Name: Attrition, dtype: float64

In [9]:
#rasio yes dan no pada y_test
y_test.value_counts()/len(y_test)

No     0.838435
Yes    0.161565
Name: Attrition, dtype: float64

Rasio terbukti sama

(3) Pada kolom numerik X_train lakukan scaling (scaler bebas)

In [10]:
#memisahkan kolom objek dan numerik pada X_train
X_train_num = X_train.select_dtypes('number')
X_train_obj = X_train.select_dtypes('object')

In [11]:
#mengecek apakah ada missing value pada X_train_num
all(X_train_num.isna().sum() == 0)

True

Karena tidak ditemukan missing value pada X_train_num maka data tersebut dapat langsung discaling dengan salah satu metode, di sini dipilih MinMax Scaling

In [12]:
minmax = MinMaxScaler()
X_train_num_scaled = pd.DataFrame(minmax.fit_transform(X_train_num), columns=minmax.feature_names_in_)
X_train_num_scaled

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,0.261905,0.503937,0.214286,0.50,0.333333,0.128571,0.666667,0.00,0.666667,0.122696,...,0.0,0.000000,0.666667,0.250,0.333333,0.666667,0.175,0.388889,0.466667,0.411765
1,0.500000,0.524696,0.642857,0.75,1.000000,0.157143,0.666667,0.25,1.000000,0.152343,...,0.0,0.333333,1.000000,0.175,0.333333,0.666667,0.050,0.111111,0.133333,0.117647
2,0.452381,0.563350,0.285714,0.50,0.333333,0.328571,0.666667,0.00,1.000000,0.069352,...,0.0,0.666667,1.000000,0.100,0.500000,0.333333,0.100,0.111111,0.066667,0.117647
3,0.023810,0.304939,0.750000,0.00,1.000000,0.285714,0.666667,0.00,0.666667,0.035071,...,0.0,1.000000,0.000000,0.000,0.333333,0.333333,0.000,0.000000,0.000000,0.000000
4,0.428571,0.560487,0.535714,0.75,0.666667,0.185714,1.000000,0.00,0.000000,0.091311,...,0.0,0.666667,0.000000,0.450,0.166667,0.666667,0.425,0.722222,1.000000,0.823529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2347,0.595238,0.585540,0.071429,0.50,0.666667,0.942857,0.000000,1.00,1.000000,0.986361,...,0.0,0.333333,0.333333,0.625,0.333333,0.666667,0.200,0.388889,0.000000,0.411765
2348,0.928571,0.351467,0.000000,0.75,1.000000,0.828571,0.666667,0.25,0.666667,0.302580,...,0.0,0.666667,0.000000,0.375,0.333333,0.666667,0.075,0.111111,0.066667,0.117647
2349,0.404762,0.372226,0.464286,0.75,0.666667,0.128571,0.333333,0.00,0.333333,0.143971,...,1.0,1.000000,0.333333,0.125,0.333333,0.000000,0.100,0.111111,0.000000,0.117647
2350,0.166667,0.355762,0.821429,0.00,0.666667,0.614286,0.000000,0.00,1.000000,0.005740,...,0.0,1.000000,0.000000,0.025,0.666667,0.666667,0.025,0.000000,0.066667,0.000000
2351,0.452381,0.823193,0.642857,0.25,0.000000,0.028571,0.666667,0.50,0.333333,0.349289,...,0.0,1.000000,0.000000,0.250,0.333333,0.666667,0.250,0.000000,0.000000,0.529412

(4) Pada kolom kategorikal X_train lakukan one hot encoding pada parameter handle_unknown beri argumen 'ignore' agar encoder robust terhadap adanya kategori di testing set yang tidak ada di training set.

In [13]:
X_train_obj.isna().sum()

BusinessTravel    0
Department        0
EducationField    0
Gender            0
JobRole           0
MaritalStatus     0
OverTime          0
dtype: int64

In [14]:
#menyiapkan transformer untuk one hot encoding kolom kategorik
ohe = OneHotEncoder(handle_unknown='ignore')
X_train_obj_ohe = pd.DataFrame(ohe.fit_transform(X_train_obj).toarray(), columns=ohe.get_feature_names_out(X_train_obj.columns))
X_train_obj_ohe

,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
4,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2347,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2348,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2349,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2350,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
2351,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0

(5) Gabungkan (menggunakan fungsi pd.concat()) hasil transformasi kolom numerik dan kategorikal X_train

In [15]:
X_train_scaled = pd.concat([X_train_num_scaled, X_train_obj_ohe], axis=1)
X_train_scaled

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
0,0.261905,0.503937,0.214286,0.50,0.333333,0.128571,0.666667,0.00,0.666667,0.122696,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.500000,0.524696,0.642857,0.75,1.000000,0.157143,0.666667,0.25,1.000000,0.152343,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.452381,0.563350,0.285714,0.50,0.333333,0.328571,0.666667,0.00,1.000000,0.069352,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.023810,0.304939,0.750000,0.00,1.000000,0.285714,0.666667,0.00,0.666667,0.035071,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
4,0.428571,0.560487,0.535714,0.75,0.666667,0.185714,1.000000,0.00,0.000000,0.091311,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2347,0.595238,0.585540,0.071429,0.50,0.666667,0.942857,0.000000,1.00,1.000000,0.986361,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2348,0.928571,0.351467,0.000000,0.75,1.000000,0.828571,0.666667,0.25,0.666667,0.302580,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2349,0.404762,0.372226,0.464286,0.75,0.666667,0.128571,0.333333,0.00,0.333333,0.143971,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2350,0.166667,0.355762,0.821429,0.00,0.666667,0.614286,0.000000,0.00,1.000000,0.005740,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
2351,0.452381,0.823193,0.642857,0.25,0.000000,0.028571,0.666667,0.50,0.333333,0.349289,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0

(7) Lakukan feature selection menggunakan multicolinearity reduction (tentukan threshold sendiri) dan mutual information. Jumlah fitur hasil seleksi bebas.

In [16]:
#menyeleksi fitur dengan multicollinearity reduction agar fitur-fitur yang akan digunakan pada model independen satu sama lain
drop = [] #list untuk menyimpan pasangan fitur yang berkorelasi tinggi
for col_1 in X_train_scaled.columns:
    for col_2 in X_train_scaled.columns:
        if col_1 != col_2:
            coef, pvalue = st.spearmanr(X_train_scaled[col_1], X_train_scaled[col_2])
            if pvalue < 0.05 and (coef < -0.8 or coef > 0.8):
                drop.append(col_1)
                drop.append(col_2)

In [17]:
unique_drop = list(set(drop))
unique_drop

['JobLevel',
 'JobRole_Human Resources',
 'Department_Human Resources',
 'Gender_Male',
 'YearsAtCompany',
 'Gender_Female',
 'YearsInCurrentRole',
 'Department_Sales',
 'JobRole_Sales Executive',
 'MonthlyIncome',
 'OverTime_Yes',
 'OverTime_No',
 'Department_Research & Development',
 'YearsWithCurrManager']

In [18]:
#drop fitur dengan multicollinearity reduction
X_train_scaled_mulred = X_train_scaled.drop(unique_drop, axis=1)
X_train_scaled_mulred

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobSatisfaction,MonthlyRate,NumCompaniesWorked,...,JobRole_Healthcare Representative,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single
0,0.261905,0.503937,0.214286,0.50,0.333333,0.128571,0.666667,0.666667,0.609958,0.333333,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,0.500000,0.524696,0.642857,0.75,1.000000,0.157143,0.666667,1.000000,0.122345,0.888889,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
2,0.452381,0.563350,0.285714,0.50,0.333333,0.328571,0.666667,1.000000,0.374102,0.111111,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.023810,0.304939,0.750000,0.00,1.000000,0.285714,0.666667,0.666667,0.992813,0.111111,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0.428571,0.560487,0.535714,0.75,0.666667,0.185714,1.000000,0.000000,0.247942,0.111111,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2347,0.595238,0.585540,0.071429,0.50,0.666667,0.942857,0.000000,1.000000,0.663762,0.333333,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
2348,0.928571,0.351467,0.000000,0.75,1.000000,0.828571,0.666667,0.666667,0.035053,0.222222,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2349,0.404762,0.372226,0.464286,0.75,0.666667,0.128571,0.333333,0.333333,0.320418,0.111111,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2350,0.166667,0.355762,0.821429,0.00,0.666667,0.614286,0.000000,1.000000,0.238747,0.111111,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2351,0.452381,0.823193,0.642857,0.25,0.000000,0.028571,0.666667,0.333333,0.109215,0.111111,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [19]:
X_train_scaled

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
0,0.261905,0.503937,0.214286,0.50,0.333333,0.128571,0.666667,0.00,0.666667,0.122696,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.500000,0.524696,0.642857,0.75,1.000000,0.157143,0.666667,0.25,1.000000,0.152343,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.452381,0.563350,0.285714,0.50,0.333333,0.328571,0.666667,0.00,1.000000,0.069352,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.023810,0.304939,0.750000,0.00,1.000000,0.285714,0.666667,0.00,0.666667,0.035071,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
4,0.428571,0.560487,0.535714,0.75,0.666667,0.185714,1.000000,0.00,0.000000,0.091311,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2347,0.595238,0.585540,0.071429,0.50,0.666667,0.942857,0.000000,1.00,1.000000,0.986361,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2348,0.928571,0.351467,0.000000,0.75,1.000000,0.828571,0.666667,0.25,0.666667,0.302580,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2349,0.404762,0.372226,0.464286,0.75,0.666667,0.128571,0.333333,0.00,0.333333,0.143971,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
2350,0.166667,0.355762,0.821429,0.00,0.666667,0.614286,0.000000,0.00,1.000000,0.005740,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
2351,0.452381,0.823193,0.642857,0.25,0.000000,0.028571,0.666667,0.50,0.333333,0.349289,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0

In [20]:
mi = mutual_info_classif(X_train_scaled_mulred, y_train, random_state=42)
mi_features = pd.DataFrame({'features': X_train_scaled_mulred.columns, 'mutual_info': mi}).sort_values(by='mutual_info', ascending=False)
mi_features

                             features  mutual_info
8                         MonthlyRate     0.086867
1                           DailyRate     0.073590
14                  TotalWorkingYears     0.042584
5                          HourlyRate     0.037981
0                                 Age     0.028018
13                   StockOptionLevel     0.025785
6                      JobInvolvement     0.024020
36               MaritalStatus_Single     0.015680
17            YearsSinceLastPromotion     0.015037
35              MaritalStatus_Married     0.013619
26    EducationField_Technical Degree     0.012658
31          JobRole_Research Director     0.011389
21     EducationField_Human Resources     0.010805
33       JobRole_Sales Representative     0.009454
16                    WorkLifeBalance     0.008957
15              TrainingTimesLastYear     0.008944
9                  NumCompaniesWorked     0.008052
22       EducationField_Life Sciences     0.007388
11                  PerformanceRating     0.007252
27  JobRole_Healthcare Representative     0.007020
4             EnvironmentSatisfaction     0.006859
19   BusinessTravel_Travel_Frequently     0.006589
18          BusinessTravel_Non-Travel     0.005510
32         JobRole_Research Scientist     0.004745
23           EducationField_Marketing     0.003843
12           RelationshipSatisfaction     0.003424
30     JobRole_Manufacturing Director     0.002972
28      JobRole_Laboratory Technician     0.001950
2                    DistanceFromHome     0.000659
7                     JobSatisfaction     0.000540
29                    JobRole_Manager     0.000163
24             EducationField_Medical     0.000000
25               EducationField_Other     0.000000
20       BusinessTravel_Travel_Rarely     0.000000
3                           Education     0.000000
34             MaritalStatus_Divorced     0.000000
10                  PercentSalaryHike     0.000000

In [21]:
drop_mi = [] #list untuk menyimpan kolom yang akan didrop
for feature, mi in zip(mi_features['features'], mi_features['mutual_info']):
    if mi < 0.01:
        drop_mi.append(feature)

In [22]:
drop_mi

['JobRole_Sales Representative',
 'WorkLifeBalance',
 'TrainingTimesLastYear',
 'NumCompaniesWorked',
 'EducationField_Life Sciences',
 'PerformanceRating',
 'JobRole_Healthcare Representative',
 'EnvironmentSatisfaction',
 'BusinessTravel_Travel_Frequently',
 'BusinessTravel_Non-Travel',
 'JobRole_Research Scientist',
 'EducationField_Marketing',
 'RelationshipSatisfaction',
 'JobRole_Manufacturing Director',
 'JobRole_Laboratory Technician',
 'DistanceFromHome',
 'JobSatisfaction',
 'JobRole_Manager',
 'EducationField_Medical',
 'EducationField_Other',
 'BusinessTravel_Travel_Rarely',
 'Education',
 'MaritalStatus_Divorced',
 'PercentSalaryHike']

In [23]:
#drop fitur berdasarkan nilai mutual_info
X_train_scaled_mulred_mi = X_train_scaled_mulred.drop(drop_mi, axis=1)
X_train_scaled_mulred_mi

,Age,DailyRate,HourlyRate,JobInvolvement,MonthlyRate,StockOptionLevel,TotalWorkingYears,YearsSinceLastPromotion,EducationField_Human Resources,EducationField_Technical Degree,JobRole_Research Director,MaritalStatus_Married,MaritalStatus_Single
0,0.261905,0.503937,0.128571,0.666667,0.609958,0.666667,0.250,0.466667,0.0,1.0,0.0,0.0,0.0
1,0.500000,0.524696,0.157143,0.666667,0.122345,1.000000,0.175,0.133333,0.0,0.0,0.0,0.0,0.0
2,0.452381,0.563350,0.328571,0.666667,0.374102,1.000000,0.100,0.066667,0.0,0.0,0.0,1.0,0.0
3,0.023810,0.304939,0.285714,0.666667,0.992813,0.000000,0.000,0.000000,0.0,0.0,0.0,0.0,1.0
4,0.428571,0.560487,0.185714,1.000000,0.247942,0.000000,0.450,1.000000,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2347,0.595238,0.585540,0.942857,0.000000,0.663762,0.333333,0.625,0.000000,0.0,0.0,1.0,1.0,0.0
2348,0.928571,0.351467,0.828571,0.666667,0.035053,0.000000,0.375,0.066667,0.0,0.0,0.0,1.0,0.0
2349,0.404762,0.372226,0.128571,0.333333,0.320418,0.333333,0.125,0.000000,0.0,0.0,0.0,0.0,0.0
2350,0.166667,0.355762,0.614286,0.000000,0.238747,0.000000,0.025,0.066667,0.0,0.0,0.0,0.0,1.0
2351,0.452381,0.823193,0.028571,0.666667,0.109215,0.000000,0.250,0.000000,0.0,0.0,0.0,0.0,1.0

(8) Lakukan semua step transformasi dan seleksi yang Anda lakukan pada X_train terhadap X_test tanpa melakukan fitting data ulang.

In [24]:
all(X_test.isna().sum() == 0) #memastikan semua kolom pada X_test tidak memiliki missing value

True

In [25]:
#memisahkan kolom objek dan numerik
X_test_num = X_test.select_dtypes('number')
X_test_obj = X_test.select_dtypes('object')

In [26]:
#transformasi minmax untuk X_test_num
X_test_num_minmax = pd.DataFrame(minmax.transform(X_test_num), columns=minmax.feature_names_in_)
X_test_num_minmax.describe()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,588.000000,588.000000,588.000000,588.000000,588.000000,588.000000,588.000000,588.000000,588.000000,588.000000,...,588.000000,588.000000,588.000000,588.000000,588.000000,588.000000,588.000000,588.000000,588.000000,588.000000
mean,0.436022,0.499625,0.292213,0.482568,0.582766,0.520335,0.580499,0.261480,0.598073,0.285877,...,0.163265,0.565760,0.272109,0.279507,0.452664,0.576531,0.176871,0.236300,0.152834,0.247199
std,0.212242,0.294719,0.284348,0.261886,0.361593,0.291983,0.226365,0.277983,0.364552,0.247717,...,0.369922,0.365593,0.296412,0.188559,0.221370,0.244572,0.156437,0.209373,0.223741,0.212062
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002212,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.285714,0.233894,0.035714,0.250000,0.333333,0.271429,0.333333,0.000000,0.333333,0.099987,...,0.000000,0.333333,0.000000,0.150000,0.333333,0.333333,0.068750,0.111111,0.000000,0.117647
50%,0.404762,0.508590,0.214286,0.500000,0.666667,0.528571,0.666667,0.250000,0.666667,0.201843,...,0.000000,0.666667,0.333333,0.250000,0.500000,0.666667,0.125000,0.166667,0.066667,0.176471
75%,0.553571,0.762706,0.464286,0.750000,1.000000,0.771429,0.666667,0.500000,1.000000,0.375158,...,0.000000,1.000000,0.333333,0.375000,0.500000,0.666667,0.231250,0.388889,0.200000,0.411765
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,0.900000,1.000000,1.000000,0.900000,1.000000,1.000000,1.000000

In [27]:
len(ohe.feature_names_in_)

7

In [28]:
ohe.transform(X_test_obj).toarray().shape

(588, 28)

In [29]:
#transformasi one hot encoding untuk X_test_obj
X_test_obj_ohe = pd.DataFrame(ohe.transform(X_test_obj).toarray(), columns=ohe.get_feature_names_out(X_test_obj.columns))
X_test_obj_ohe

,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
584,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
585,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
586,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
587,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [30]:
#menggabungkan kedua jenis X_test
X_test_transformed = pd.concat([X_test_num_minmax, X_test_obj_ohe], axis=1)
#menyeleksi fitur X_test yang telah ditransformasi dengan fitur pada X_train_scaled_mulred_mi
X_test_selected = X_test_transformed[X_train_scaled_mulred_mi.columns]
all(X_test_selected.columns == X_train_scaled_mulred_mi.columns) #mengecek apakah kolom pada X_train dan X_test yang sudah diseleksi sudah sama

True

(9) Siapkan 6 variabel:** <p>
(i) X_train paska transformasi TANPA seleksi, <p>
(ii) X_test paska transformasi TANPA seleksi, <p>
(iii) X_train paska transformasi DENGAN seleksi, <p>
(iv) X_test paska transformasi DENGAN seleksi, <p>
(v) y_train <p>
(vi) y_test <p>

Print output dari metode .head() dan atribut shape dari masing-masing variabel di atas.<p>

<p>
**pada hands-on logistic regression akan dibandingkan performance model tanpa seleksi fitur vs dengan seleksi fitur

In [37]:
#X_train pascatransformasi tanpa seleksi
print(X_train_scaled.shape)
X_train_scaled.head()

(2352, 51)

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
0,0.261905,0.503937,0.214286,0.50,0.333333,0.128571,0.666667,0.00,0.666667,0.122696,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,0.500000,0.524696,0.642857,0.75,1.000000,0.157143,0.666667,0.25,1.000000,0.152343,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.452381,0.563350,0.285714,0.50,0.333333,0.328571,0.666667,0.00,1.000000,0.069352,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.023810,0.304939,0.750000,0.00,1.000000,0.285714,0.666667,0.00,0.666667,0.035071,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
4,0.428571,0.560487,0.535714,0.75,0.666667,0.185714,1.000000,0.00,0.000000,0.091311,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [38]:
#X_test pascatransformasi tanpa seleksi
print(X_test_transformed.shape)
X_test_transformed.head()

(588, 51)

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,OverTime_No,OverTime_Yes
0,0.238095,0.798139,0.000000,0.50,0.666667,0.528571,0.666667,0.00,0.000000,0.135966,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.000000,0.951324,0.464286,0.50,0.333333,0.042857,0.666667,0.00,0.666667,0.026593,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
2,0.523810,0.367931,0.035714,0.25,0.666667,0.985714,0.666667,0.00,0.000000,0.124697,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.142857,0.421618,0.785714,0.50,0.333333,0.842857,1.000000,0.00,1.000000,0.090363,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,0.523810,0.744452,0.250000,0.25,1.000000,0.600000,0.666667,0.25,1.000000,0.161137,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [39]:
#X_train pascatransformasi dengan seleksi
print(X_train_scaled_mulred_mi.shape)
X_train_scaled_mulred_mi.head()

(2352, 13)

,Age,DailyRate,HourlyRate,JobInvolvement,MonthlyRate,StockOptionLevel,TotalWorkingYears,YearsSinceLastPromotion,EducationField_Human Resources,EducationField_Technical Degree,JobRole_Research Director,MaritalStatus_Married,MaritalStatus_Single
0,0.261905,0.503937,0.128571,0.666667,0.609958,0.666667,0.250,0.466667,0.0,1.0,0.0,0.0,0.0
1,0.500000,0.524696,0.157143,0.666667,0.122345,1.000000,0.175,0.133333,0.0,0.0,0.0,0.0,0.0
2,0.452381,0.563350,0.328571,0.666667,0.374102,1.000000,0.100,0.066667,0.0,0.0,0.0,1.0,0.0
3,0.023810,0.304939,0.285714,0.666667,0.992813,0.000000,0.000,0.000000,0.0,0.0,0.0,0.0,1.0
4,0.428571,0.560487,0.185714,1.000000,0.247942,0.000000,0.450,1.000000,0.0,0.0,0.0,0.0,1.0

In [40]:
#X_test pascatransformasi dengan seleksi
print(X_test_selected.shape)
X_test_selected.head()

(588, 13)

,Age,DailyRate,HourlyRate,JobInvolvement,MonthlyRate,StockOptionLevel,TotalWorkingYears,YearsSinceLastPromotion,EducationField_Human Resources,EducationField_Technical Degree,JobRole_Research Director,MaritalStatus_Married,MaritalStatus_Single
0,0.238095,0.798139,0.528571,0.666667,0.426621,0.333333,0.075,0.066667,0.0,0.0,0.0,1.0,0.0
1,0.000000,0.951324,0.042857,0.666667,0.237864,0.000000,0.000,0.000000,0.0,0.0,0.0,0.0,1.0
2,0.523810,0.367931,0.985714,0.666667,0.944027,0.333333,0.175,0.000000,0.0,0.0,0.0,1.0,0.0
3,0.142857,0.421618,0.842857,1.000000,0.784421,0.666667,0.150,0.066667,0.0,0.0,0.0,1.0,0.0
4,0.523810,0.744452,0.600000,0.666667,0.270909,0.000000,0.200,0.133333,0.0,0.0,0.0,0.0,0.0

In [41]:
print(y_train.shape)
y_train.head()

(2352,)

932     Yes
1335     No
294      No
127     Yes
752     Yes
Name: Attrition, dtype: object

In [42]:
print(y_test.shape)
y_test.head()

(588,)

2777    No
1311    No
2756    No
474     No
2568    No
Name: Attrition, dtype: object

In [50]:
X_train_scaled.to_csv('X_train_transformed.csv')

In [51]:
X_train_scaled_mulred_mi.to_csv('X_train_selected.csv')

In [52]:
X_test_transformed.to_csv('X_test_transformed.csv.')

In [53]:
X_test_selected.to_csv('X_test_selected.csv')

In [54]:
y_train.to_csv('y_train.csv')

In [55]:
y_test.to_csv('y_test.csv')